service: lbh-social-care

provider:
  name: aws
  runtime: nodejs14.x
  versionFunctions: false
  region: eu-west-2
  stage: ${opt:stage}
  deploymentBucket:
    name: ${self:custom.deploymentBucket.${self:custom.environmentName}}

package:
  individually: true
  exclude:
    - ./**

functions:
  lbh-social-care:
    name: ${self:service}-${self:provider.stage}
    handler: lambda.handler
    timeout: 30
    package:
      include:
        - lambda.js
        - next.config.js
        - pages/**
        - public/**
        - build/_next/**
        - node_modules/**
    events:
      - http:
          path: api/{proxy+}
          method: ANY
      - http: ANY /
      - http: ANY /{proxy+}
    provisionedConcurrency: 5
    vpc:
      securityGroupIds: ${self:custom.securityGroups.${self:custom.environmentName}}
      subnetIds: ${self:custom.subnets.${self:custom.environmentName}}
    environment:
      AWS_KEY: ${ssm:/lbh-social-care/${self:custom.ssmEnvironmentName}/aws-key}
      ENDPOINT_API: ${ssm:/lbh-social-care/${self:custom.ssmEnvironmentName}/endpoint-case-viewer}
      GSSO_URL: ${ssm:/lbh-social-care/${self:custom.ssmEnvironmentName}/gsso-url}
      GSSO_TOKEN_NAME: ${ssm:/lbh-social-care/${self:custom.ssmEnvironmentName}/gsso-token-name}
      HACKNEY_JWT_SECRET: ${ssm:/lbh-social-care/${self:custom.ssmEnvironmentName}/hackney-jwt}
      AUTHORISED_DEV_GROUP: ${ssm:/lbh-social-care/${self:custom.ssmEnvironmentName}/authorised-dev-group}
      AUTHORISED_ADMIN_GROUP: ${ssm:/lbh-social-care/${self:custom.ssmEnvironmentName}/authorised-admin-group}
      AUTHORISED_ADULT_GROUP: ${ssm:/lbh-social-care/${self:custom.ssmEnvironmentName}/authorised-adult-group}
      AUTHORISED_CHILD_GROUP: ${ssm:/lbh-social-care/${self:custom.ssmEnvironmentName}/authorised-child-group}
      AUTHORISED_ALLOCATORS_GROUP: ${ssm:/lbh-social-care/${self:custom.ssmEnvironmentName}/authorised-allocators-group}
      AUTHORISED_UNRESTRICTED_GROUP: ${ssm:/lbh-social-care/${self:custom.ssmEnvironmentName}/authorised-unrestricted-group}
      POSTCODE_LOOKUP_URL: ${ssm:/lbh-social-care/${self:custom.ssmEnvironmentName}/postcode-lookup-url}
      POSTCODE_LOOKUP_APIKEY: ${ssm:/lbh-social-care/${self:custom.ssmEnvironmentName}/postcode-lookup-apikey}
      NEXT_PUBLIC_FEEDBACK_LINK: ${ssm:/lbh-social-care/${self:custom.ssmEnvironmentName}/next-public-feedback-link}
      REDIRECT_URL: ${ssm:/lbh-social-care/${self:custom.ssmEnvironmentName}/redirect_url}
      NEXT_PUBLIC_GOOGLE_ANALYTICS_ID: ${ssm:/lbh-social-care/${self:custom.ssmEnvironmentName}/next_public_google_analytics_id}
resources:
  Resources:
    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Aliases:
            - ${self:custom.aliases.${self:custom.environmentName}}
          PriceClass: PriceClass_100
          ViewerCertificate:
            AcmCertificateArn: ${self:custom.certificate-arn.${self:custom.environmentName}}
            MinimumProtocolVersion: TLSv1.2_2018
            SslSupportMethod: sni-only
          DefaultCacheBehavior:
            TargetOriginId: ${self:service}-${self:provider.stage}-custom-origin
            ViewerProtocolPolicy: 'redirect-to-https'
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - PATCH
              - POST
              - DELETE
            DefaultTTL: 0
            MaxTTL: 0
            MinTTL: 0
            ForwardedValues:
              QueryString: true
              Cookies:
                Forward: all
          Enabled: true
          Origins:
            - Id: ${self:service}-${self:provider.stage}-custom-origin
              DomainName: ${self:custom.domain-name}
              OriginPath: /${self:provider.stage}
              CustomOriginConfig:
                HTTPPort: 80
                HTTPSPort: 443
                OriginProtocolPolicy: https-only

custom:
  namedEnvironments:
    staging: staging
    production: production
  environmentName: ${self:custom.namedEnvironments.${self:provider.stage}, 'preview'}
  ssmEnvironmentName: ${self:custom.namedEnvironments.${self:provider.stage}, 'staging'} # TODO: Remove, add SSM keys, and use environmentName
  domain-name:
    Fn::Join:
      - '.'
      - - Ref: ApiGatewayRestApi
        - execute-api
        - eu-west-2
        - amazonaws.com
  deploymentBucket:
    preview: lbh-social-care-preview-serverless-deployment-bucket
    staging: lbh-social-care-staging-serverlessdeploymentbucke-1d3k4v28ktkc9
    production: lbh-social-care-producti-serverlessdeploymentbuck-1gtigiratk9ir
  aliases:
    preview: social-care-service-preview-${self:provider.stage}.hackney.gov.uk # TODO: can this be a sub-domain? May need to update certificate alternate domain
    staging: social-care-service-staging.hackney.gov.uk
    production: social-care-service.hackney.gov.uk
  certificate-arn:
    preview: arn:aws:acm:us-east-1:715003523189:certificate/8f7fa30c-a4e5-4775-b827-ade824a33c9a
    staging: arn:aws:acm:us-east-1:715003523189:certificate/8f7fa30c-a4e5-4775-b827-ade824a33c9a
    production: arn:aws:acm:us-east-1:153306643385:certificate/71728a39-cd3e-4570-a440-e87f84ef9a0d
  securityGroups:
    preview:
      - sg-048f0fb9620e30710
    staging:
      - sg-048f0fb9620e30710
    production:
      - sg-082581136513324b1
  subnets:
    preview:
      - subnet-06d3de1bd9181b0d7
      - subnet-0ed7d7713d1127656
    staging:
      - subnet-06d3de1bd9181b0d7
      - subnet-0ed7d7713d1127656
    production:
      - subnet-0b7b8fea07efabf34
      - subnet-01d3657f97a243261
